"""xterm.js color themes for Butterfly.

Each theme is a dict matching the xterm.js ITheme interface.
Served via /api/themes endpoint and applied client-side.
"""

THEMES: dict[str, dict[str, str]] = {
    "default": {
        "background": "#1a1a2e",
        "foreground": "#e0e0e0",
        "cursor": "#e0e0e0",
        "selectionBackground": "rgba(255, 255, 255, 0.2)",
    },
    "dracula": {
        "background": "#282a36",
        "foreground": "#f8f8f2",
        "cursor": "#f8f8f2",
        "selectionBackground": "#44475a",
        "black": "#21222c",
        "red": "#ff5555",
        "green": "#50fa7b",
        "yellow": "#f1fa8c",
        "blue": "#bd93f9",
        "magenta": "#ff79c6",
        "cyan": "#8be9fd",
        "white": "#f8f8f2",
        "brightBlack": "#6272a4",
        "brightRed": "#ff6e6e",
        "brightGreen": "#69ff94",
        "brightYellow": "#ffffa5",
        "brightBlue": "#d6acff",
        "brightMagenta": "#ff92df",
        "brightCyan": "#a4ffff",
        "brightWhite": "#ffffff",
    },
    "solarized-dark": {
        "background": "#002b36",
        "foreground": "#839496",
        "cursor": "#839496",
        "selectionBackground": "#073642",
        "black": "#073642",
        "red": "#dc322f",
        "green": "#859900",
        "yellow": "#b58900",
        "blue": "#268bd2",
        "magenta": "#d33682",
        "cyan": "#2aa198",
        "white": "#eee8d5",
        "brightBlack": "#586e75",
        "brightRed": "#cb4b16",
        "brightGreen": "#586e75",
        "brightYellow": "#657b83",
        "brightBlue": "#839496",
        "brightMagenta": "#6c71c4",
        "brightCyan": "#93a1a1",
        "brightWhite": "#fdf6e3",
    },
    "solarized-light": {
        "background": "#fdf6e3",
        "foreground": "#657b83",
        "cursor": "#657b83",
        "selectionBackground": "#eee8d5",
        "black": "#073642",
        "red": "#dc322f",
        "green": "#859900",
        "yellow": "#b58900",
        "blue": "#268bd2",
        "magenta": "#d33682",
        "cyan": "#2aa198",
        "white": "#eee8d5",
        "brightBlack": "#002b36",
        "brightRed": "#cb4b16",
        "brightGreen": "#586e75",
        "brightYellow": "#657b83",
        "brightBlue": "#839496",
        "brightMagenta": "#6c71c4",
        "brightCyan": "#93a1a1",
        "brightWhite": "#fdf6e3",
    },
    "monokai": {
        "background": "#272822",
        "foreground": "#f8f8f2",
        "cursor": "#f8f8f0",
        "selectionBackground": "#49483e",
        "black": "#272822",
        "red": "#f92672",
        "green": "#a6e22e",
        "yellow": "#f4bf75",
        "blue": "#66d9ef",
        "magenta": "#ae81ff",
        "cyan": "#a1efe4",
        "white": "#f8f8f2",
        "brightBlack": "#75715e",
        "brightRed": "#f92672",
        "brightGreen": "#a6e22e",
        "brightYellow": "#f4bf75",
        "brightBlue": "#66d9ef",
        "brightMagenta": "#ae81ff",
        "brightCyan": "#a1efe4",
        "brightWhite": "#f9f8f5",
    },
    "nord": {
        "background": "#2e3440",
        "foreground": "#d8dee9",
        "cursor": "#d8dee9",
        "selectionBackground": "#434c5e",
        "black": "#3b4252",
        "red": "#bf616a",
        "green": "#a3be8c",
        "yellow": "#ebcb8b",
        "blue": "#81a1c1",
        "magenta": "#b48ead",
        "cyan": "#88c0d0",
        "white": "#e5e9f0",
        "brightBlack": "#4c566a",
        "brightRed": "#bf616a",
        "brightGreen": "#a3be8c",
        "brightYellow": "#ebcb8b",
        "brightBlue": "#81a1c1",
        "brightMagenta": "#b48ead",
        "brightCyan": "#8fbcbb",
        "brightWhite": "#eceff4",
    },
    "aether": {
        "background": "#0a0e14",
        "foreground": "#b3b1ad",
        "cursor": "#e6b450",
        "selectionBackground": "#253340",
        "black": "#01060e",
        "red": "#ea6c73",
        "green": "#91b362",
        "yellow": "#f9af4f",
        "blue": "#53bdfa",
        "magenta": "#fae994",
        "cyan": "#90e1c6",
        "white": "#c7c7c7",
        "brightBlack": "#686868",
        "brightRed": "#f07178",
        "brightGreen": "#c2d94c",
        "brightYellow": "#ffb454",
        "brightBlue": "#59c2ff",
        "brightMagenta": "#ffee99",
        "brightCyan": "#95e6cb",
        "brightWhite": "#ffffff",
    },
}


def get_theme(name: str) -> dict[str, str]:
    """Get a theme by name, falling back to default."""
    return THEMES.get(name, THEMES["default"])
